### PR TITLE
Add scoop installation instructions

### PR DESCRIPTION
**Pull request by igitur**
Dependent on https://github.com/ScoopInstaller/Main/pull/5696

### CODE REVIEW

**Comment by pacman82** [comment]
Okay, cool! Never heard about scoop so far. Can we merge this,  or would we need to wait on the dependent PR?

**Comment by igitur** [comment]
I think let's wait for it to land up in scoop repo first. I see i have some feedback to address.

BTW, scoop is great, better than chocolatey IMHO.

And thanks for a great tool!

**Comment by pacman82** [comment]
Minor thing here. You placed the hint to scoop in the `Prerequisites` section. Although it is Windows specific I would tend to move it to the other installation channels, together with the GitHub binary downloads and installation via `cargo`. There we can have a short statement that scoop is a package manager for Windows. What do you think?

**Comment by igitur** [comment]
Haha, that's not so minor. Total oversight on my end. I'll adjust.

**Review by pacman82 — APPROVED** [review]

**Comment by pacman82** [comment]
Now, it's good. The only thing missing then, is that it should be true, i.e. the request in the scoop repository needs to be merged.

**Comment by igitur** [comment]
https://github.com/ScoopInstaller/Main/pull/5696 is merged now.

**Comment by igitur** [comment]
Bonus points if you can do a similar Rust based `odbc2csv` tool ;-)

**Comment by pacman82** [comment]
* https://crates.io/search?q=odbcsv
* https://github.com/pacman82/odbc-api/releases/tag/odbcsv1.0.5

It shares its repository with `odbc-api` ;-). All tags with `odbcsv` in front do release it though. The version tags release the `crate` (Rust library) itself.

**Comment by igitur** [comment]
Ah, I saw the repo, but didn't go into the releases section. Thanks!

**Comment by pacman82** [comment]
Go to tags not releases, stopped doing GitHub releases a while ago

**Pull request merged**
