### PR TITLE
Specify minimum supported rust version

### PR DESCRIPTION
**Pull request by alippai**

### CODE REVIEW

**Comment by pacman82** [comment]
Thanks for the contribution. I feel this promise should go hand in hand with also fixing the rust version within the GitHub actions build pipeline. Otherwise I would be prone to breaking it by accident. Could you add this to this PR or would you need help with that?

Cheers, Markus

**Comment by alippai** [comment]
I can try it later today. I don't have experience with GitHub actions, but if it doesn't need special permissions I should be able to handle this task.

**Comment by pacman82** [comment]
Just switch `stable` with `1.49.0` in the build.yml. If it still builds on your branch everything is fine.

**Comment by alippai** [comment]
About the permissions: the actions are not run on pull requests, I was wondering how to trigger it for this repo or the fork.

**Comment by alippai** [comment]
I've figured it out, the build output looks good to me - added the pull_requests to the GitHub action triggers.

**Comment by pacman82** [comment]
Thanks!

**Pull request merged**
